version: '3.4'

services:
  mongoclient:
    container_name: mongoclient
    image: mongoclient/mongoclient
    ports:
      - '3000:3000'

  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    depends_on:
      - mongoclient

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - '6379:6379'

  orderdb:
    container_name: orderdb
    environment:
      SA_PASSWORD: 'fakePassword@N0tReal'
      ACCEPT_EULA: 'Y'
    restart: always
    ports:
      - '1433:1433'

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=fakePassword
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgressql/data/

  portainer:
    container_name: portainer
    restart: always
    ports:
      - '8080:8000'
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=fakePassword
    restart: always
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/root/.pgadmin

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - 'DatabaseSettings:ConnectionString=mongodb://catalogdb:27017'
    depends_on:
      - catalogdb
    ports:
      - '8000:80'
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - 'CacheSettings:ConnectionString=basketdb:6379'
      - 'GrpcSettings:DiscountUrl=http://discount.grpc'
      - 'EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672'
    ports:
      - '8001:80'
    depends_on:
      - basketdb
      - rabbitmq

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=fakePassword;"
    depends_on:
      - discountdb
    ports:
      - '8002:80'

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=fakePassword;"
    depends_on:
      - discountdb
    ports:
      - '8003:80'

  order.api:
    container_name: order.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - 'ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=fakePassword@N0tReal;TrustServerCertificate=true;'
      - 'EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672'
    depends_on:
      - orderdb
      - rabbitmq
    ports:
      - '8004:80'

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - catalog.api
      - basket.api
      - discount.api
      - order.api
    ports:
      - "8010:80"

  shopping.aggregator:
    container_name: shopping.aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - 'ApiSettings_CatalogUrl=http://catalog.api'
      - 'ApiSettings_BasketUrl=http://basket.api'
      - 'ApiSettings_OrderUrl=http://order.api'

    ports:
      - "8005:80"

